### ISSUE TITLE
NoClassDefFoundError R$layout

### ISSUE THREAD

**Issue by fbrier** [kolavar/android-support-v4-preferencefragment#16]
I am sure I am doing something wrong, but after struggling with this for a couple of days, I am hoping opening an issue will provide a resolution.  I included the android-support-v4-preferencefragment in my Maven project as a dependency.  When I attempt to run my application, it throws a NoClassDefFoundError for android.support.v4.preferencefragment.R$layout.  Looking at the .aar file included in the downloaded zip, there is no R.class file, or an R$layout.class file (for the inner static class).  I attempted to build it myself and while a BuildConfig.class is included, no R.class.  Being more familiar with Maven than Gradle, I created a pom.xml and built the project, and again, no R.class.  So suspecting that it was not the build tool, but an Android tool behavior that was the problem, I went on the android-dev IRC channel.  A gentleman named pfn informed me that the .aar spec does not allow for R.class(s) to be in an .aar.  So it is filtering out the R.class.  But if that is the case, then obviously I am using this library incorrectly.  Could someone please let me know why this might be happening?  Below is the stack trace:

    java.lang.NoClassDefFoundError: android.support.v4.preferencefragment.R$layout
            at android.support.v4.preference.PreferenceFragment.onCreateView(PreferenceFragment.java:95)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1177)
            at android.app.Activity.performStart(Activity.java:5468)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
            at android.app.ActivityThread.access$900(ActivityThread.java:174)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5593)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by fbrier** [comment]
It turns out that this was a set of bugs in both my SDK version, apktools and IntelliJ, compounding my confusion with previously resolved bugs in the Maven plugin.  I am actually using an EAP release of IntelliJ (14.0.4 EAP) that finally resolved the problems.  All of this caused by Google Android's design choices to both change the directory tree structure (moving assets, res, libs, and the AndroidManifest.xml) and the .aar format not allowing R classes, which has caused cascading problems in these tools for the last 1-1/2 years.  Thank you Android team.
